# Generated by Django 5.2.15 on 2026-09-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone_number',
        ),
    ]
