# Generated by Django 5.2.15 on 2026-09-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_doctor_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_direct_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_cancellation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_new_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('contacts', 'Contacts Only')], default='public', max_length=20),
        ),
    ]
