# Generated by Django 5.2.15 on 2026-08-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
