# Generated by Django 5.2.15 on 2026-08-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('diagnostics', '0002_alter_diagnostictest_options_and_more'),
        ('doctors', '0002_alter_doctorschedule_unique_together_and_more'),
        ('patients', '0001_initial'),
        ('reports', '0002_alter_medicalreport_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalreport',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_type',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Diagnostic', 'Diagnostic')], default='Medical', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='test_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_report', to='diagnostics.testbooking'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='patients.patientprofile'),
        ),
    ]
