# Generated by Django 5.2.15 on 2026-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_medicalreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/%Y/%m/'),
        ),
    ]
