# Generated by Django 5.2.15 on 2026-09-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_medicalreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='report_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Published', max_length=20),
        ),
    ]
