# Generated by Django 5.2.15 on 2026-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_medicalreport_diagnostic_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='advice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
