# Generated by Django 5.2.15 on 2026-09-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Doctor Registration', 'Doctor Registration'), ('Doctor Approved', 'Doctor Approved'), ('Doctor Rejected', 'Doctor Rejected'), ('Appointment', 'Appointment'), ('Payment', 'Payment'), ('Report', 'Report'), ('Diagnostic', 'Diagnostic'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
