# Generated by Django 5.2.15 on 2026-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0004_alter_doctorschedule_options_alter_timeslot_options_and_more'),
        ('patients', '0002_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, default='', help_text='Patient symptoms (Optional)'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-appointment_date'], name='appointment_patient_49b41f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['slot', 'appointment_date'], name='appointment_slot_id_01d4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booking_number'], name='appointment_booking_e77601_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'appointment_date', 'slot'), name='unique_patient_doctor_slot_date'),
        ),
    ]
