# Generated by Django 5.2.15 on 2026-09-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_aisymptomreportpayment'),
        ('doctors', '0013_allow_empty_doctor_registration'),
        ('patients', '0005_patientprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_patient_doctor_slot_family_date',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'appointment_date', 'slot', 'family_member'), name='unique_patient_doctor_slot_date'),
        ),
    ]
