# Generated by Django 5.2.15 on 2026-08-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day'), name='unique_doctor_schedule_day'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('schedule', 'slot_time'), name='unique_schedule_slot_time'),
        ),
    ]
