# Generated by Django 5.2.15 on 2026-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__first_name', 'user__username'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['doctor', 'day'], 'verbose_name': 'Doctor Schedule', 'verbose_name_plural': 'Doctor Schedules'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['slot_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='max_patient_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Maximum patients allowed in each generated slot.'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of each appointment slot in minutes.'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_patient',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of patients allowed.'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_count__gte', 0)), name='booked_count_non_negative'),
        ),
    ]
