# Generated by Django 5.2.15 on 2026-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_options_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['doctor', 'day', 'start_time'], 'verbose_name': 'Doctor Schedule', 'verbose_name_plural': 'Doctor Schedules'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['schedule', 'slot_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='max_patient_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of patients allowed in each time slot.'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Appointment duration in minutes. Example: 15, 20, 30, 45, 60.'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='max_patient',
            field=models.PositiveIntegerField(default=1, help_text='Maximum patients allowed in this slot.'),
        ),
    ]
