# Generated by Django 5.2.15 on 2026-09-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctorschedule_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
