# Generated by Django 5.2.15 on 2026-09-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_approval_status_doctor_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
