# Generated by Django 5.2.15 on 2026-09-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_address_doctor_date_of_birth_doctor_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
    ]
