# Generated by Django 5.2.15 on 2026-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
