# Generated by Django 5.2.15 on 2026-09-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payment_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Partial', 'Partial Payment'), ('Full', 'Full Payment')], default='Full', max_length=20),
        ),
    ]
