# Generated by Django 5.2.15 on 2026-08-26 11:31

import diagnostics.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostictest',
            options={'ordering': ['name'], 'verbose_name': 'Diagnostic Test', 'verbose_name_plural': 'Diagnostic Tests'},
        ),
        migrations.AlterModelOptions(
            name='testbooking',
            options={'ordering': ['-booking_date', '-booking_time', '-created_at'], 'verbose_name': 'Test Booking', 'verbose_name_plural': 'Test Bookings'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ['name'], 'verbose_name': 'Test Category', 'verbose_name_plural': 'Test Categories'},
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='booking_number',
            field=models.CharField(default=diagnostics.models.generate_test_booking_number, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='diagnostic_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='diagnostics.diagnostictest'),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_bookings', to='patients.familymember'),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_bookings', to='patients.patientprofile'),
        ),
    ]
